"""Regenerate the compact ES/NQ CFTC TFF module from the official API."""

from __future__ import annotations

import base64
import json
import struct
import zlib
from datetime import date, datetime
from pathlib import Path
from urllib.parse import quote
from urllib.request import urlopen

DATASET = "https://publicreporting.cftc.gov/resource/gpe5-46if.json"
CODES = ("13874+", "20974+")
FIELDS = (
    "report_date_as_yyyy_mm_dd",
    "open_interest_all",
    "dealer_positions_long_all",
    "dealer_positions_short_all",
    "asset_mgr_positions_long",
    "asset_mgr_positions_short",
    "lev_money_positions_long",
    "lev_money_positions_short",
    "nonrept_positions_long_all",
    "nonrept_positions_short_all",
    "dealer_positions_spread_all",
    "asset_mgr_positions_spread",
    "lev_money_positions_spread",
)
BASE_DATE = date(2010, 1, 1)


def fetch(code: str) -> list[dict[str, str]]:
    where = quote(
        f"cftc_contract_market_code='{code}' AND "
        "report_date_as_yyyy_mm_dd>='2010-01-01T00:00:00.000'",
        safe="='>",
    )
    url = (
        f"{DATASET}?$limit=5000&$select={','.join(FIELDS)}"
        f"&$where={where}&$order=report_date_as_yyyy_mm_dd"
    )
    with urlopen(url, timeout=60) as response:
        return json.load(response)


def pack(rows: list[dict[str, str]]) -> str:
    payload = bytearray()
    previous_day = None
    previous_values = None
    for row in rows:
        report_date = datetime.fromisoformat(row[FIELDS[0]].replace("Z", "+00:00")).date()
        open_interest = float(row["open_interest_all"])
        values = [
            (float(row[long_key]) - float(row[short_key])) / open_interest
            for long_key, short_key in (
                ("dealer_positions_long_all", "dealer_positions_short_all"),
                ("asset_mgr_positions_long", "asset_mgr_positions_short"),
                ("lev_money_positions_long", "lev_money_positions_short"),
                ("nonrept_positions_long_all", "nonrept_positions_short_all"),
            )
        ]
        values.extend(
            float(row[key]) / open_interest
            for key in (
                "dealer_positions_spread_all",
                "asset_mgr_positions_spread",
                "lev_money_positions_spread",
            )
        )
        quantized = [round(value * 10_000) for value in values]
        day = (report_date - BASE_DATE).days
        if previous_day is None:
            payload.extend(struct.pack("<Hhhhhhhh", day, *quantized))
        else:
            day_change = day - previous_day
            changes = [value - previous for value, previous in zip(quantized, previous_values)]
            payload.extend(struct.pack("<Bhhhhhhh", day_change, *changes))
        previous_day = day
        previous_values = quantized
    return base64.b64encode(zlib.compress(bytes(payload), level=9)).decode()


def render(grouped: dict[str, list[dict[str, str]]]) -> str:
    blobs = {code: pack(rows) for code, rows in grouped.items()}
    return f'''"""Embedded official CFTC TFF weekly positions for ES/NQ (2010 onward).

Generated by tools/build_cftc_tff_embedded.py from CFTC dataset gpe5-46if.
Ratios are quantized to one basis point. Report dates are Tuesdays; consumers
must apply the publication lag before using a row.
"""

import base64
import struct
import zlib
from datetime import date

_ES_B64 = """{blobs["13874+"]}"""
_NQ_B64 = """{blobs["20974+"]}"""


def load_tff_rows():
    base_date = date(2010, 1, 1)
    grouped = {{}}
    for code, payload in (("13874+", _ES_B64), ("20974+", _NQ_B64)):
        raw = zlib.decompress(base64.b64decode(payload))
        rows = []
        day, *current = struct.unpack_from("<Hhhhhhhh", raw, 0)
        offset = 16
        decoded = [(day, current)]
        while offset < len(raw):
            day_change, *changes = struct.unpack_from("<Bhhhhhhh", raw, offset)
            day += day_change
            current = [value + change for value, change in zip(current, changes)]
            decoded.append((day, current.copy()))
            offset += 15
        for day, values in decoded:
            dealer, asset_mgr, lev_money, nonrept, dspread, aspread, lspread = values
            rows.append({{
                "report_date": base_date.fromordinal(base_date.toordinal() + day),
                "dealer": dealer / 10_000.0,
                "asset_mgr": asset_mgr / 10_000.0,
                "lev_money": lev_money / 10_000.0,
                "nonrept": nonrept / 10_000.0,
                "dealer_spread": dspread / 10_000.0,
                "asset_mgr_spread": aspread / 10_000.0,
                "lev_money_spread": lspread / 10_000.0,
            }})
        grouped[code] = rows
    return grouped
'''


def main() -> None:
    destination = Path(__file__).parents[1] / "quantconnect" / "cftc_tff_embedded.py"
    grouped = {code: fetch(code) for code in CODES}
    destination.write_text(render(grouped), encoding="utf-8")
    print({code: len(rows) for code, rows in grouped.items()})
    print(f"wrote {destination} ({destination.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
